SISPTD/SISPTD/Controllers/PericiaController.cs
using System;
using System.Net;
using System.Web.Mvc;
using SISPTD.Models;
using SISPTD.BO;

namespace SISPTD.Controllers
{
    public class PericiaController : Controller
    {
        private ProcessoBO processoBO = new ProcessoBO(new dbSISPTD());
        private PericiaBO periciaBO = new PericiaBO(new dbSISPTD());
        private PessoaBO pessoBO = new PessoaBO(new dbSISPTD());
        private MovimentacaoBO movimentacaoBO = new MovimentacaoBO(new dbSISPTD());
        private UserBO usuarioBO = new UserBO(new dbSISPTD());



        public ActionResult Index(int? pagina)
        {
            int tamanhoPagina = 10;
            int numeroPagina = pagina ?? 1;

            return View(periciaBO.ObterPericia(numeroPagina, tamanhoPagina));
        }

        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pericia pericia = periciaBO.SelecionarPorId(id.Value);
            if (pericia == null)
            {
                return HttpNotFound();
            }
            return View(pericia);
        }

        public ActionResult Create(int? processoId)
        {
            var usuario = usuarioBO.userLogado(User.Identity.Name);
            ViewBag.usuarioRecebuId = usuario.usuarioId;
            if (processoId != null )
            {
                processoBO.AlteraUsuarioDoProcesso(usuario.usuarioId, processoId.Value);

            }
            if (processoId != null)
            {
                Processo objProcesso = processoBO.SelecionarPorId(processoId.Value);
               
                Pessoa objPaciente = objProcesso.Paciente;
                ViewBag.processoId = objProcesso.processoId;
                ViewBag.pacienteCpf = objPaciente.cpf;
                ViewBag.pacienteNome = objPaciente.nome;
                ViewBag.pacienteId = objPaciente.pessoaId;

            }
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(int ? usuarioRecebeuId, int? pacientepessoaId, Pericia pericia)
        {
            try
            {

                if (!periciaBO.VerificaPericia(pericia))
                {
                    
                    processoBO.AlteraUsuarioDoProcesso(usuarioRecebeuId.Value, pericia.processoId);
                    pericia.dt_Pericia = DateTime.Now;
                    periciaBO.Inserir(pericia);
                    TempData["Sucesso"] = "Pericia Cadastrada com Sucesso";
                    return RedirectToAction("Index", new { tab = "profile" });
                }
                else
                {
                    TempData["Erro"] = "Esse Processo já foi Periciado";
                  return  RedirectToAction("Index");
                }
               
               
            }
            catch (Exception ex)
            {
                TempData["Erro"] = "Ops ! " + ex.Message;
            }
            return View(pericia);
        }

        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pericia pericia = periciaBO.SelecionarPorId(id.Value);
            if (pericia == null)
            {
                return HttpNotFound();
            }
            return View(pericia);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "periciaId,descricao,cidId,dt_Pericia,medicoId,situacao,pessoaId")] Pericia pericia)
        {
            if (ModelState.IsValid)
            {
                periciaBO.Alterar(pericia);
                return RedirectToAction("Index");
            }
            return View(pericia);
        }

        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pericia pericia = periciaBO.SelecionarPorId(id.Value);
            if (pericia == null)
            {
                return HttpNotFound();
            }
            return View(pericia);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            periciaBO.ExcluirPorId(id);
            return RedirectToAction("Index");
        }

       
    }
}

SISPTD/SISPTD/Views/Pericia/Create.cshtml
@model SISPTD.Models.Pericia
@{
    ViewBag.Title = "Pericia Medica";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel panel-default">
        <div class="panel-heading">
            <h5 class="panel-title"> <i class="fa fa-list-alt fa-lg" aria-hidden="true"></i> <strong>Pericia</strong></h5>

        </div>

        <div class="panel-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("N° Processo", htmlAttributes: new { @class = "control-label" })
                    <div class="input-group">
                        <input type="number" id="buscarPacientePericia" class="processo form-control" name="processoId" value="@ViewBag.processoId" />

                      @*  @Html.TextBox("buscarPacientePericia", (string)@ViewBag.pacienteCpf, Request.QueryString["CPF"], new { autofocus = "", @class = " procuraPacientePericia  col-md-2 form-control ", placeholder = "Procure  pelo N° do Processo " })*@
                        <span class="input-group-btn"><button type="button" id="btnBuscaPacPericia" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("CPF", htmlAttributes: new { @class = "control-labe" })
                        <input type="text" id="pacienteCpf" readonly class="form-control" name="cpf" value="@ViewBag.pacienteCpf" />
                    </div>
                </div>    
                <div class="col-md-7">
                    <div class="form-group">
                        @Html.Label("Paciente", htmlAttributes: new { @class = "control-labe" })
                        <input type="text" readonly id="nomeDoPacientePericia" data-id="" class="form-control " name="Paciente" value="@ViewBag.pacienteNome" />
                        <input type="hidden" id="idDoPacientePericia" name="pacientepessoaId" value="@ViewBag.pacienteId" />
                        <input type="hidden" name="usuarioRecebeuId" value="@ViewBag.usuarioRecebuId" />


                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.Label("Descrição *", htmlAttributes: new { @class = "control-label" })
                        @Html.TextAreaFor(model => model.descricao, 5, 175, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
         

            @*<div class="row">
                <div class="col-md-12">
                    @Html.Label("Descrição *", htmlAttributes: new { @class = "control-label" })
                    <div class="form-group">
                            @Html.TextAreaFor(model => model.descricao, 5, 175, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Situacao, htmlAttributes: new { @class = "control-label" })
                        @Html.EnumDropDownListFor(model => model.Situacao, "", htmlAttributes: new { @class = "form-control chosen-select" })
                        @Html.ValidationMessageFor(model => model.Situacao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="form-group">
                        @Html.Label("Selecione", htmlAttributes: new { @class = "control-label" })
                          
                        <div class="panel panel-default">
                            <div class="panel-body">
                                @Html.Label("Primeira Vez", htmlAttributes: new { @class = "control-label" })
                                @Html.RadioButtonFor(model => model.TipoPericia, "Primeira Vez")
                                @Html.Label("Retorno")
                                @Html.RadioButtonFor(model => model.TipoPericia, "Retorno")
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-md-6 col-sm-8">
                    <div class="form-group">
                        @Html.Label("Codigo CID")
                        @Html.DropDownList("cidId", new List<SelectListItem>(), " ", new { @class = "form-control", data_url = @Url.Action("PesquisaCid", "Cid") })
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h5><i class="panel-title fa fa-user-md fa-lg" aria-hidden="true"></i> <strong> Dados do Medico da Pericia</strong></h5>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-5">
                        </div>
                        <div id="btCriaMedico" style="display:none" class="alert alert-warning alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            Ops! Não foi Possivel localizar o  Medico Deseja Cadastra-lo:.
                            <a title="Cadastrar Medico" class="btn btn-primary" href="@Url.Action("CreateMedico", "Pessoa")">Cadastrar Medico</a>
                        </div>
                    </div>





                    <div class="row">
                        <div class="col-md-3">
                            @Html.Label("CPF", htmlAttributes: new { @class = "control-label" })
                            <div class="input-group">
                                @Html.TextBox("buscarMedico", Request.QueryString["CPF"], new { @class = " procurarMedico cpf col-md-2 form-control ", placeholder = "Procure por CPF" })
                                <span class="input-group-btn"><button type="button" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button></span>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                @Html.Label("Nome", htmlAttributes: new { @class = "control-labe" })
                                <input type="text" readonly id="nomeDoMedico" data-id="" class="form-control " name="name" />
                                <input type="hidden" id="idDoMedico" name="medicoPessoaId" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.Label("Telefone", htmlAttributes: new { @class = "control-label" })
                                <input type="text" readonly id="telDoMedico" data-id="" class="form-control " name="telDoMedico" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.Label("Celular", htmlAttributes: new { @class = "control-label" })
                                <input type="text" readonly id="celDoMedico" data-id="" class="form-control " name="celDoMedico" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.Label("Cartão do SUS", htmlAttributes: new { @class = "control-label" })
                                <input type="text" readonly id="cnsDoMedico" data-id="" class="form-control cns " name="cnsDoMedico" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                @Html.Label("CRM", htmlAttributes: new { @class = "control-labe" })
                                <input type="text" readonly id="crmDoMedico" data-id="" class="form-control " name="crmDoMedico" />
                            </div>
                        </div>
                    </div>

                </div>
            </div>
           
        </div>
    </div>

    <div class="well well-sm">
        <button type="submit" name="name" class="btn btn-primary "> <i class="fa fa-floppy-o fa-lg"></i>  Gravar</button>
        <a class="btn btn-success pull-right" href="@Url.Action("Index","Pericia")"> <i class="fa fa-backward fa-lg"></i>  Voltar para Lista </a>
    </div>
}
<script>
    var urlBuscaPacPericia = '@Url.Action("BuscaProcesso", "Processo")';
    var urlBuscarMedico = '@Url.Action("PesquisarMedico", "Pessoa")';
</script>

SISPTD/SISPTD/Views/Pericia/Delete.cshtml
@model SISPTD.Models.Pericia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pericia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cid.codigoCid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cid.codigoCid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Medico.crm_Medico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medico.crm_Medico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pessoa.cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pessoa.cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_Pericia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_Pericia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.situacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.situacao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SISPTD/SISPTD/Views/Pericia/Details.cshtml
@model SISPTD.Models.Pericia
@{
    Layout = "~/Views/Shared/_LayoutPrint.cshtml";
    ViewBag.Title = "Pericia";
}


<h2 class="text-center"><i class="fa fa-stethoscope" aria-hidden="true"></i> Pericia - Tratamento fora Domicilio</h2>
<div>
    <h2> Processo Nº @Html.DisplayFor(model => model.Processo.processoId) </h2>
       
     
        <table class="table table-condensed table-bordered">
            <tr>
                <th colspan="5" class="active">
                    <h3  class="text-center">@Html.DisplayFor(model => model.Processo.Paciente.nome)</h3>
                </th>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.cpf)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.rg)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.orgaoemissor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.dt_Emissao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.cns)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.cpf)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.rg)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.orgaoemissor)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.dt_Emissao)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.cns)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.nome_Mae)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.nome_Pai)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.tel)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.cel)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Processo.Paciente.email)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.nome_Mae)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.nome_Pai)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.tel)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.cel)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Processo.Paciente.email)
                </td>
            </tr>
           
        </table>

   
   
    <table class="table table-condensed table-bordered">
        <tr>
            <th colspan="4" class="active">
                <h3 class="text-center "> Médico</h3>
            </th>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Processo.Medico.cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Processo.Medico.nome)
            </th>


            <th>
                @Html.DisplayNameFor(model => model.Processo.Medico.cns)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Processo.Medico.crm)
            </th>
        </tr>
        <tr>

            <td>
                @Html.DisplayFor(model => model.Processo.Medico.cpf)
            </td>
            <td>
                @Html.DisplayFor(model => model.Processo.Medico.nome)
            </td>


            <td>
                @Html.DisplayFor(model => model.Processo.Medico.cns)
            </td>
            <td>
                @Html.DisplayFor(model => model.Processo.Medico.crm)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Processo.Medico.tel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Processo.Medico.cel)
            </th>
            <th colspan="2">
                @Html.DisplayNameFor(model => model.Processo.Medico.email)
            </th>

        </tr>
        <tr>

            <td>
                @Html.DisplayFor(model => model.Processo.Medico.tel)
            </td>
            <td>
                @Html.DisplayFor(model => model.Processo.Medico.cel)
            </td>
            <td colspan="2">
                @Html.DisplayFor(model => model.Processo.Medico.email)
            </td>
        </tr>

    </table>
  
    <div class="row">
        
        <table class="table table-condensed table-bordered">
            <tr>
                <th colspan="5" class="active">
                    <h3 class="text-center active">Dados da Pericia</h3>
                </th>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Cid.codigoCid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cid.descricao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoPericia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Situacao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.dt_Pericia)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Cid.codigoCid)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Cid.descricao)
                </td>
                <td>
                    @Html.DisplayFor(model => model.TipoPericia)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Situacao)
                </td>
                <td>
                    @Html.DisplayFor(model => model.dt_Pericia)
                </td>
            </tr>
            <tr>
                <th colspan="5">
                    @Html.DisplayNameFor(model => model.descricao)
                </th>
            </tr>
            <tr>
                <td colspan="5">
                    @Html.DisplayFor(model => model.descricao)
                </td>
            </tr>
        </table>
        </div>
    </div>

SISPTD/SISPTD/Views/Pericia/Edit.cshtml
@model SISPTD.Models.Pericia
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()



 
    <div class="form-horizontal">
        <h4>Pericia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.periciaId)
        <div class="form-group">
            @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.cidId, "cidId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("cidId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.cidId, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.dt_Pericia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dt_Pericia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dt_Pericia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Medico", new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Medico.nome, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>
        <div class="form-group">
            <div class="form-group">
                @Html.LabelFor(model => model.Situacao, htmlAttributes: new { @class = "control-label" })
                @Html.EnumDropDownListFor(model => model.Situacao, "", htmlAttributes: new { @class = "form-control chosen-select" })
                @Html.ValidationMessageFor(model => model.Situacao, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.pessoaId, "pessoaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("pessoaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.pessoaId, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
  
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
  

SISPTD/SISPTD/Views/Pericia/Index.cshtml
@model PagedList.IPagedList<SISPTD.Models.Pericia>
@using PagedList.Mvc
@{
    ViewBag.Title = "Pericia Medica";
}

<h3><i class="fa fa-list-alt"></i> Pericia Medica</h3>

<div>
    <a class="btn  btn-primary" title="Criar Nova Pericia" href="@Url.Action("Create", "Pericia")" aria-label="Skip to main navigation">
        <i class="fa fa-plus fa-lg" aria-hidden="true"></i> Nova Pericia
    </a>
</div>
<br />

    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Processos Para Pericia</a></li>
            <li role="presentation"><a href="#profile"  role="tab" data-toggle="tab">Lista de Percias</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="home">
                @Html.Action("ProcessoEmPericia", "Processo")
            </div>
            <div  class="tab-pane" id="profile">

                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><h5> <i class="fa fa-user fa-lg"> </i> <strong>Lista de Pericias Medicas</strong>   </h5></div>

                    <!-- Table -->
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered table-condensed">
                            <tr>
                                <th>
                                    @Html.DisplayName("N° Processo")
                                </th>
                                <th>
                                    @Html.DisplayName("CPF")
                                </th>
                                <th>
                                    @Html.DisplayName("Paciente")
                                </th>
                                <th>
                                    @Html.DisplayName("Código Cid")
                                </th>
                                <th>
                                    @Html.DisplayName("Data da Pericia")
                                </th>

                                <th>
                                    @Html.DisplayName("Ação")

                                </th>
                            </tr>

                            @foreach (var item in Model)
            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Processo.processoId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Processo.Paciente.cpf)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Processo.Paciente.nome)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Cid.codigoCid)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.dt_Pericia)
                                    </td>

                                    <td>
                                       
                                        <a class="btn-group btn-sm btn-primary" title="Imprimir" href="@Url.Action("Details", "Pericia",new { id= item.periciaId })", target="_blank" aria-label="Skip to main navigation">
                                            <i class="fa fa-print fa-lg" aria-hidden="true"></i>
                                        </a>
                                        <a class="btn-group btn-sm btn-primary" title="Distribuir" href="@Url.Action("Create","Movimentacao", new {id = item.processoId })" aria-label="Skip to main navigation">
                                            <i class="fa fa-exchange fa-lg" aria-hidden="true"></i>
                                        </a>
                                       
                                    </td>
                                </tr>

                            }


                        </table>
                    </div>

                </div>


                
                <div class="pull-right">
                    <strong>  Pagina @Model.PageNumber de @Model.PageCount </strong>
                    @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, tab="profile" }))
                </div>
            </div>
          
        </div>
    </div>



@section Scripts{
    <script>

        function qs(name) {
            name = name.replace(/[\[]/, "\\[").replace(/[\]]/,"\\]");
            var regex = new RegExp("[\\?&]" + name +"=([^&#]*)"),
            results = regex.exec(location.search);
            return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g,""));
        }

        var tab = qs("tab");

        if (tab == "profile") 
        {
            $('.nav-tabs li:eq(1) a').tab('show')
        }

        console.log(qs("tab"))
    </script>
}