SISPTD/SISPTD/Controllers/RequisicaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SISPTD.Models;
using SISPTD.BO;
using SISPTD.Ultis;

namespace SISPTD.Controllers
{
    public class RequisicaoController : Controller
    {
        private PessoaBO pessoaBO = new PessoaBO(new dbSISPTD());
        private RequisicaoBO requisicaoBO = new RequisicaoBO(new dbSISPTD());
        private UserBO usuarioBO = new UserBO(new dbSISPTD());
        private CidadeBO cidadeBO = new CidadeBO(new dbSISPTD());
        private CidBO cidBO = new CidBO(new dbSISPTD());
        private PessoaRequisicaoBO pessoaRequisicaoBO = new PessoaRequisicaoBO(new dbSISPTD());
        private EstadoBO ufBO = new EstadoBO(new dbSISPTD());

        public ActionResult Index(int? pagina, string busca="")
        {
            int tamanhoPagina = 10;
            int numeroPagina = pagina ?? 1;
            busca = Util.RemoverMascara(busca);
            return View(requisicaoBO.ObterRequisicao(numeroPagina, tamanhoPagina, busca));
        }
        /// <summary>
        /// Adiciona acompanhate na requisição
        /// </summary>
        /// <param name="pacienteId"></param>
        /// <param name="id"></param>
        /// <param name="Pessoa"></param>
        /// <returns></returns>
        public ActionResult AddAcompanhante(long? pacienteId, int id, List<Pessoa> Pessoa)
        {
            try
            {
                if (pacienteId != null)
                {
                    Pessoa acompanhante = pessoaBO.SelecionarPorId(id);
                    Pessoa paciente = pessoaBO.SelecionarPorId(pacienteId.Value);
                    if (paciente.pessoaId == acompanhante.acompanhanteId)
                    {
                        Pessoa = Pessoa ?? new List<Pessoa>();

                        if (Pessoa.Count() < 3)
                        {
                            Pessoa.Add(acompanhante);
                            return PartialView("_ListaPessoa", Pessoa);
                        }
                        else
                        {
                            TempData["Erro"] = "Só é permitido três Acompanhante!";
                        }

                    }
                    else
                    {
                        TempData["Erro"] = "A pessoa pesquisada não é Acomptanhante de " + paciente.nome;
                    }

                }
                else
                {
                    TempData["Erro"] = "Não existe paciente para o Acompanhante pesquisado!";
                }
            }
            catch (Exception ex)
            {
                TempData["Erro"] = "Ops! " + ex.Message;
            }

            return PartialView("_ErrosSystem");
        }
        public ActionResult RemoveAcompanhante(int id, List<Pessoa> Pessoa)
        {
            var acompanhante = Pessoa[id];
            Pessoa = Pessoa ?? new List<Pessoa>();
            Pessoa.Remove(acompanhante);
            return PartialView("_ListaPessoa", Pessoa);
        }

        public ActionResult Print(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Requisicao requisicao = requisicaoBO.SelecionarPorId(id.Value);
            if (requisicao == null)
            {
                return HttpNotFound();
            }
            return View(requisicao);

        }

        public ActionResult Create()
        {
            ViewBag.Estado = new SelectList(ufBO.Selecionar(), "IdEstado", "Sigla");
            ViewBag.IdCidadesDestino = new SelectList("", "IdCidade", "Cidade");
            ViewBag.IdCidadesOrigem = new SelectList("", "IdCidade", "Cidade");
            ViewBag.usuarioId = new SelectList(usuarioBO.Selecionar(), "usuarioId", "login");
            Requisicao requisicao = new Requisicao();
            return View(requisicao);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Requisicao requisicao, int? pessoaId, List<Pessoa> Pessoa)
        {
            try
            {
                if ( pessoaId == null || pessoaId == 0 )
                {
                    TempData["Erro"] = "Preencha as informações do paciente !";
                    return RedirectToAction("Create");
                }
                
                List<Pessoa> ListaDeAcompanhante = new List<Pessoa>();
                if (Pessoa != null && Pessoa.Any())
                {
                    foreach (var acompanhante in Pessoa)
                    {
                        ListaDeAcompanhante.Add(pessoaBO.SelecionarPorId(acompanhante.pessoaId));
                    }
                }

                var usuario = usuarioBO.userLogado(User.Identity.Name);
                requisicao.usuarioId = usuario.usuarioId;
                if (ModelState.IsValid)
                {
                    if (requisicao.IdCidadesDestino == 0 || requisicao.IdCidadesDestino == requisicao.IdCidadesOrigem )
                    {
                        TempData["Erro"] = "Cidade Destino não pode ser Nula ou Igual a cidade de Origem";
                        return View(requisicao);
                    }
                    requisicao.pacienteId = pessoaId.Value;
                    requisicao.dtRequisicao = DateTime.Now;
                    requisicaoBO.Inserir(requisicao);

                    int i = 0;
                    List<PessoaRequisicao> ListaPessoaRequisicao = new List<Models.PessoaRequisicao>();
                    foreach (var item in ListaDeAcompanhante)
                    {
                        ListaPessoaRequisicao.Add(new PessoaRequisicao
                        {
                            pessoaId = item.pessoaId,
                            requisicaoId = requisicao.requisicaoId,
                            TipoPessoa = TipoPessoa.Acompanhante,
                        });
                        i++;
                    }
                    if (ListaPessoaRequisicao.Count > 0)
                    {
                        pessoaRequisicaoBO.InserirLista(ListaPessoaRequisicao);
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                throw;
            }

            ViewBag.IdCidadesDestino = new SelectList(cidadeBO.Selecionar(), "IdCidade", "Cidade", requisicao.IdCidadesDestino);
            ViewBag.IdCidadesOrigem = new SelectList(cidadeBO.Selecionar(), "IdCidade", "Cidade", requisicao.IdCidadesOrigem);
            ViewBag.usuarioId = new SelectList(usuarioBO.Selecionar(), "usuarioId", "login", requisicao.usuarioId);
            return View(requisicao);
        }
      
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Requisicao requisicao = requisicaoBO.SelecionarPorId(id.Value);
            if (requisicao == null)
            {
                return HttpNotFound();
            }
            return View(requisicao);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            requisicaoBO.ExcluirPorId(id);
            return RedirectToAction("Index");
        }
       

        

    }
}

SISPTD/SISPTD/Views/Requisicao/Create.cshtml
@model SISPTD.Models.Requisicao

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Requição";
}


@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    @* Inicio do panel *@

    <div class="panel panel-default">
        <div class="panel panel-heading" >
           
            <h4 class="panel-title"><i class="fa fa-plane fa-lg" aria-hidden="true"></i> Requisição de Viajem</h4>
        
        </div> 
        
        <div class="panel-body">
            <span class="text-danger pull-right"><i class="fa fa-info-circle "></i> Os campos com o marcador (*)  são de preenchimento obrigatório.</span>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="panel-body">
               
                <div class="row">
                    <div class="col-md-3">
                        @Html.Label("CPF *", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group">
                            @Html.TextBox("buscarPaciente", Request.QueryString["CPF"], new { autofocus = "", @class = " procurarPaciente cpf  form-control ", placeholder = "Procure por CPF" })
                            <span class="input-group-btn"><button type="button" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button></span>
                        </div>
                    </div>
                    <div class="col-md-9">
                        @Html.Label("Nome *", htmlAttributes: new { @class = "control-label" })
                        <div class="form-group">
                            <input type="text" readonly id="nomeDoPaciente" data-id="" class="form-control " name="name" />
                            <input type="hidden" id="idDoPaciente" name="pessoaId" />
                            @Html.ValidationMessageFor(model => model.pacienteId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"> <strong>Origem *</strong></h3>
                            </div>
                            <div class="panel-body">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("UF", htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownList("Estado", null, "UF", new { @class = "chosen-select uf-change form-control", data_target_select = "#IdCidadesOrigem", data_url = Url.Action("PesquisaCidade", "Cidade") })
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    @Html.Label("Cidade", htmlAttributes: new { @class = "control-label" })
                                    @Html.DropDownList("IdCidadesOrigem", null, "UF Primeiro", new { @class = "chosen-select form-control" })
                                    @Html.ValidationMessageFor(model => model.IdCidadesOrigem, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"> <strong>Destino *</strong></h3>
                            </div>
                            <div class="panel-body">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("UF", htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownList("Estado", null, "UF", new { @class = "chosen-select uf-change form-control", data_target_select = "#IdCidadesDestino", data_url = Url.Action("PesquisaCidade", "Cidade") })
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    @Html.Label("Cidade", htmlAttributes: new { @class = "control-label" })
                                    @Html.DropDownList("IdCidadesDestino", null, "UF Primeiro", new { @class = "chosen-select form-control" })
                                    @Html.ValidationMessageFor(model => model.IdCidadesOrigem, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"> <strong>Informações *</strong></h3>
                            </div>
                            <div class="panel-body">
                                <div class="form-group col-md-6">
                                    @Html.LabelFor(model => model.Trecho, htmlAttributes: new { @class = "control-label" })
                                    @Html.EnumDropDownListFor(model => model.Trecho, htmlAttributes: new { @class = "form-control chosen-select" })
                                    @Html.ValidationMessageFor(model => model.Trecho, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-md-6">
                                    @Html.LabelFor(model => model.Via, htmlAttributes: new { @class = "control-label" })
                                    @Html.EnumDropDownListFor(model => model.Via, htmlAttributes: new { @class = "form-control chosen-select" })
                                    @Html.ValidationMessageFor(model => model.Via, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10 ">
                        <div class="form-group">

                            <!-- Dispara o Modal-->
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                                @*<i class="fa fa-plus" aria-hidden="true"></i>*@
                                <i class="fa fa-user-plus fa-lg" aria-hidden="true"></i> <Strong>Adicionar Acompanhantes</Strong>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            @Html.Label("Observações *", htmlAttributes: new { @class = "control-label" })
                            @Html.TextAreaFor(model => model.observacoes, 5, 175, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.observacoes, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @*<div class="row">
                    <div class="col-sm-10 col-md-10">
                        <div class="form-group">
                            @Html.Label("Observações *", htmlAttributes: new { @class = "control-label " })
                            @Html.TextAreaFor(model => model.observacoes, 5, 146, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.observacoes, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@

            </div>

            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel"> <i class="fa fa-user-plus fa-lg" aria-hidden="true"></i> <Strong>Adicionar Acompanhantes</Strong></h4>
                        </div>
                        <div class="modal-body">
                            <input type="hidden" id="pessoa_id_pai" name="pessoaId" />
                            <input type="hidden" name="idPai" id="idPai" />
                           @* <input type="hidden" class="cpf" name="cpfAcomp" id="cpfAcomp" value="" />*@
                            <span class="input-group">
                                <input type="text" name="buscar" id="buscar" class="form-control cpf" value="" />
                               @* @Html.TextBox("buscar", Request.QueryString["CPF"], new { value="", Styles="display:nome;", autofocus = "", @class = "procurarPessoa  col-md-2 form-control", placeholder = "Procure por CPF" })*@
                                <span class="input-group-btn">
                                    <button type="button" id="procurarAcompanhentes" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </span>

                            </span>
                            <hr />

                            <h3 class="text-center"> <label id="nome_pessoa" data-id="" class="paciente text-center" name="name" /> </h3>
                        </div>
                        <div class="modal-footer">
                            <a href="#" onclick="AddPessoaLista();" data-dismiss="modal" data-id="" data-url="@Url.Action("AddAcompanhante", "Requisicao") " id="AddItens" class="btn btn-success acompId "><i class="glyphicon glyphicon-plus"></i> </a>
                            @*<a href="#" onclick="Limpar();" id="btnLimpar" class="btn btn-success ">
                                    <i class="fa fa-eraser" aria-hidden="true"></i>
                                </a>*@
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div id="divItens" class="panel-body ">
            @Html.Partial("_ListaPessoa", Model.PessoaAcompanhante ?? new List<SISPTD.Models.Pessoa>())
        </div>

    </div>
    <div class="well well-sm">
        <button type="submit" name="name" class="btn btn-primary "> <i class="fa fa-floppy-o fa-lg"></i>  Gravar</button>
        <a class="btn btn-danger pull-right" href="@Request.UrlReferrer"> <i class="fa fa-arrow-left fa-lg"></i>  Voltar para Lista </a>
    </div>

}

<script>
    var urlRequisicao = '@Url.Action("Pesquisar","Pessoa")';
</script>

SISPTD/SISPTD/Views/Requisicao/Delete.cshtml
@model SISPTD.Models.Requisicao

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Requisicao</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Agendamento.agendamentoId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Agendamento.agendamentoId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CidadeDestino.Cidade)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CidadeDestino.Cidade)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CidadeOrigem.Cidade)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CidadeOrigem.Cidade)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Usuario.login)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Usuario.login)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.dtRequisicao)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.dtRequisicao)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.observacoes)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.observacoes)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.via)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.via)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.trecho)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.trecho)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

SISPTD/SISPTD/Views/Requisicao/Index.cshtml
@model PagedList.IPagedList<SISPTD.Models.Requisicao>
@using PagedList.Mvc
@{
    ViewBag.Title = "Requisição de Passagem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<h3>
    <i class="fa fa-plane" aria-hidden="true"></i> Requisição de Viajem
    <a class="btn btn-primary" href="@Url.Action("Create","Requisicao")"><i class="fa fa-plus" aria-hidden="true"></i></a>
   
</h3>*@
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4  col-md-offset-4">

        @using (Html.BeginForm(FormMethod.Get))
            {

            <div class="input-group ">
                <div class="input-group-btn">
                    <a href="@Url.Action("Create")" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> Novo</a>
                </div>
                @Html.TextBox("busca", Request.QueryString["busca"], new { autofocus = "", @class = " form-control", placeholder = "Procure por CPF ou CNS" })
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        }

    </div>
</div>

<div class="row">
    <div class="col-md-12">
        



    </div>
</div>
<br />

@*<span class="col-sm-6 col-md-4 pull-right">
    @using (Html.BeginForm(FormMethod.Get))
            {

        <span class="input-group ">
            @Html.TextBox("busca", Request.QueryString["busca"], new { autofocus = "", @class = " form-control", placeholder = "Procure por CPF ou CNS" })
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </span>
        </span>
    }
</span>*@

@if (Model.Any() && Model != null)
{
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><h3 class="panel-title"><i class="fa fa-list fa-lg" aria-hidden="true"></i> <strong> Lista de Requisição</strong></h3></div>
        <div class="table-responsive">
            <!-- Table -->
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayName("Origem")
                        </th>
                        <th>
                            @Html.DisplayName("Destino")
                        </th>
                        <th>
                            @Html.DisplayName("Paciente")
                        </th>
                        <th>
                            @Html.DisplayName("Data da Requisição")
                        </th>
                       
                        <th>
                            @Html.DisplayName("Via")
                        </th>
                        <th>
                            @Html.DisplayName("Trecho")
                        </th>
                        <th>
                            @Html.DisplayName("Ação")
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CidadeOrigem.Cidade)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CidadeDestino.Cidade)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Paciente.nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.dtRequisicao)
                            </td>
                           
                            <td>
                                @Html.DisplayFor(modelItem => item.Via)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Trecho)
                            </td>
                            <td>
                                
                                <a title="Imprimir" href="@Url.Action("Print", "Requisicao", new { id=item.requisicaoId })" target="_blank"> <span class="fa fa-print fa-lg"></span> </a>
                            </td>
                        </tr>

                }
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="pull-right">
        <strong>Pagina @Model.PageNumber de @Model.PageCount</strong>
        @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina }))
    </div>
}
else
{
    <br />
    <h2 class="text-center text-muted">
        
        <small>
            NENHUMA<br />

            REQUISIÇÃO ENCONTRADA
        </small>
    </h2>
}

SISPTD/SISPTD/Views/Requisicao/_ListaPessoa.cshtml
@model IEnumerable<SISPTD.Models.Pessoa>
@if (Model != null && Model.Any())
{
    <div class="panel panel-default">
        <div class="panel panel-heading"><strong> <i class="fa fa-users" aria-hidden="true"></i> Acompanhantes</strong></div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.cpf)
                        </th>
                        <th>
                            @Html.DisplayName("Acompanhante")
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.dt_Nascimento)
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.idade)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.cns)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.tel)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.cel)
                        </th>
                        <th></th>
                        <th>
                            @Html.DisplayName("Remover")
                        </th>
                        <th></th>
                    </tr>

                    @{var pos = 0;}
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.cpf)
                                <input type="hidden" class="removeAcompanhante" value="@item.pessoaId" name="Pessoa[@pos].pessoaId" />
                                <input type="hidden" class="cpfAcompanhante" value="@item.cpf" name="Pessoa[@pos].cpf" />
                                <input type="hidden" value="@item.nome_Pai" name="Pessoa[@pos].nome_Pai" />
                                <input type="hidden" value="@item.nome_Mae" name="Pessoa[@pos].nome_Mae" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.nome)
                                <input type="hidden" value="@item.nome" name="Pessoa[@pos].nome" />
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.dt_Nascimento)
                                <input type="hidden" value="@item.dt_Nascimento" name="Pessoa[@pos].dt_Nascimento" />
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.idade)
                                <input type="hidden" value="@item.idade" name="Pessoa[@pos].idade" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.cns)
                                <input type="hidden" value="@item.cns" name="Pessoa[@pos].cns" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tel)
                                <input type="hidden" value="@item.tel" name="Pessoa[@pos].tel" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.cel)
                                <input type="hidden" value="@item.cel" name="Pessoa[@pos].cel" />
                            </td>
                            <td></td>
                            <td class="text-center">
                                <a href="#" onclick="RemoveAcompanhanteLista();" data-dismiss="modal" data-id="@pos" data-url="@Url.Action("RemoveAcompanhante", "Requisicao") " id="RemoveItens" class="acompId "> <i class="glyphicon glyphicon-remove"></i> </a>
                            </td>
                        </tr>


                        pos++;
                    }
                </table>
            </div>

        </div>
    </div>
                    }