SISPTD/SISPTD/Controllers/PessoaController.cs
using SISPTD.BO;
using SISPTD.Models;
using SISPTD.Ultis;
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace SISPTD.Controllers
{
    public class PessoaController : Controller
    {
        private PessoaBO pessoaBO = new PessoaBO(new dbSISPTD());
        private CidadeBO cidadeBO = new CidadeBO(new dbSISPTD());
        private EnderecoBO enderecoBO = new EnderecoBO(new dbSISPTD());


        public ActionResult Index(int? pagina, string busca = "")
        {
            int tamanhoPagina = 10;
            int numeroPagina = pagina ?? 1;
            busca = Util.RemoverMascara(busca);
            return View(pessoaBO.ObterPessoa(busca, numeroPagina, tamanhoPagina));
        }
        /// <summary>
        /// Busca um Paciente quando passado um CPF
        /// </summary>
        /// <param name="cpf">string cpf</param>
        /// <returns>Json</returns>
       
        public ActionResult Pesquisar(string cpf)
        {
            cpf = Util.RemoverMascara(cpf);
            if (!string.IsNullOrEmpty(cpf))
            {
                var pessoa = pessoaBO.Selecionar().Where(p => p.cpf.Contains(cpf) || p.cns.Contains(cpf) ).FirstOrDefault();
                if (pessoa == null || pessoa.TipoPessoa == TipoPessoa.Medico)
                {
                    return Json(new { Nome = "", Id = 0 }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Nome = pessoa.nome, Id = pessoa.pessoaId, Cpf = pessoa.cpf }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(null);
            }
           
        }
        public ActionResult PesquisarMedico(string cpf)
        {
            cpf = Util.RemoverMascara(cpf);
            var pessoa = pessoaBO.Selecionar().Where(p => p.cpf == cpf && p.TipoPessoa == TipoPessoa.Medico).FirstOrDefault();
            if (pessoa == null)
            {
                return Json(new { Nome = "", Id = 0, Cpf = "", Cns = "", Tel = "", Cel = "", Crm = "" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Nome = pessoa.nome, Id = pessoa.pessoaId, Cpf = pessoa.cpf, Tel = pessoa.tel, Cel = pessoa.cel, Crm = pessoa.crm, Cns = pessoa.cns }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Details(long? id)
        {
            ViewBag.acompanhante = pessoaBO.Selecionar().Where(a => a.acompanhanteId == id.Value).Take(5);

            return View(pessoaBO.SelecionarPorId(id.Value));
        }
        [Authorize(Roles = "Funcionario, Gerente, Administrador")]
        public ActionResult Create()
        {
            ViewBag.cidade = new SelectList(cidadeBO.Selecionar(), "IdCidade", "Cidade");
            return View();
        }
        /// <summary>
        /// Action que cria uma pessoa do tipo Paciente e retorna para Action Index 
        /// </summary>
        /// <param name="pessoa">pessoa</param>
        /// <returns>Action</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Funcionario, Gerente, Administrador")]
        public ActionResult Create(Pessoa pessoa)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    pessoa.TipoPessoa = TipoPessoa.Paciente;
                    pessoa.cpf = Util.RemoverMascara(pessoa.cpf);
                    pessoa.cns = Util.RemoverMascara(pessoa.cns);
                    pessoa.dt_Cadastro = DateTime.Now;
                    if (pessoaBO.CalculoIdade(pessoa))
                    {
                        pessoaBO.Inserir(pessoa);
                        TempData["Erro"] = "O Cadastro do Paciente requer um Acompanhante!";
                        return RedirectToAction("CreateAcompanhante", new { acompanhanteId = pessoa.pessoaId });

                    }
                    pessoaBO.Inserir(pessoa);
                    TempData["Sucesso"] = "Cadastrado Realizado com Sucesso!";
                    pessoaBO.SelecionarPorId(pessoa.pessoaId);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["Erro"] = "Ops! " + e.Message;
            }

            ViewBag.cidade = new SelectList(cidadeBO.Selecionar(), "IdCidade", "Cidade");
            ViewBag.pessoaPai = new SelectList(pessoaBO.Selecionar(), "pessoaId", "cpf", pessoa.acompanhanteId);
            return View(pessoa);
        }
        public ActionResult CreateAcompanhante(long? acompanhanteId)
        {
            try
            {
                if (acompanhanteId != null)
                {
                    if (ModelState.IsValid)
                    {
                        Pessoa acompanhante = new Pessoa();
                        acompanhante.acompanhanteId = acompanhanteId;
                        ViewBag.pessoaId = acompanhanteId;
                        return View(acompanhante);
                    }
                }
            }
            catch (Exception)
            {
                TempData["Erro"] = "Ops! erro durante o Cadastro do Acompanhante!";
            }

            ViewBag.pessoaId = 0;
            return View();
        }
        /// <summary>
        /// Action Responsavel por criar Uma Pessoa do Tipo Acompanhante Retornando
        /// </summary>
        /// <param name="pessoa">pessoa</param>
        /// <param name="acompanhanteId">id do acompanhante</param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult CreateAcompanhante(Pessoa pessoa, long? acompanhanteId)
        {
            try
            {
                pessoa.cpf = Ultis.Util.RemoverMascara(pessoa.cpf);
                pessoa.acompanhanteId = acompanhanteId;

                if (ModelState.IsValid)
                {
                    pessoa.TipoPessoa = TipoPessoa.Acompanhante;
                    pessoa.dt_Cadastro = DateTime.Now;
                    if (pessoaBO.CalculoIdade(pessoa))
                    {
                        TempData["Erro"] = "Ops! O acompanhate não deve ser menor de 18 ou maior de 60 anos !";
                        return View(pessoa);
                    }
                    pessoaBO.Inserir(pessoa);
                    TempData["Sucesso"] = "Acompanhante Cadastrado com Sucesso !";
                    return RedirectToAction("Edit", new { id = pessoa.acompanhanteId });
                }
            }
            catch (Exception ex)
            {

                TempData["Erro"] = "Erro durante o Cadastro de Acompanhante " + ex.Message;
            }

            return View();
        }
        public ActionResult EditarAcompanhante(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoa = pessoaBO.SelecionarPorId(id.Value);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult EditarAcompanhante(Pessoa pessoa)
        {
            try
            {
                pessoa.cns = Ultis.Util.RemoverMascara(pessoa.cns);
                pessoa.cpf = Ultis.Util.RemoverMascara(pessoa.cpf);
                if (ModelState.IsValid)
                {
                    Endereco objEndereco = enderecoBO.SelecionarPorId(pessoa.Endereco.enderecoId);
                    objEndereco.cep = pessoa.Endereco.cep;
                    objEndereco.rua = pessoa.Endereco.rua;
                    objEndereco.numero = pessoa.Endereco.numero;
                    objEndereco.bairro = pessoa.Endereco.bairro;
                    pessoa.TipoPessoa = TipoPessoa.Acompanhante;
                    pessoaBO.CalculoIdade(pessoa);
                    pessoaBO.Alterar(pessoa);
                    enderecoBO.Alterar(objEndereco);
                    TempData["Sucesso"] = "Alteração Realizada com Sucesso!";
                }
                return RedirectToAction("Details", new { id = pessoa.acompanhanteId });
            }
            catch (Exception ex)
            {
                TempData["Erro"] = "Ops! Ocorreu um erro!" + ex.Message;
            }
            return View(pessoa);
        }


        #region Crud Funcionario
        [Authorize(Roles = "Gerente, Administrador")]
        public ActionResult ListaDeFuncionario(int? pagina, string buscaFuncionario = "")
        {
            int tamanhoPagina = 10;
            int numeroPagina = pagina ?? 1;
            buscaFuncionario = Util.RemoverMascara(buscaFuncionario);

            return View(pessoaBO.ObterFuncionarios(buscaFuncionario, numeroPagina, tamanhoPagina));
        }
        [Authorize(Roles = "Gerente, Administrador")]
        public ActionResult CreateFuncionario()
        {
            return View();
        }
        /// <summary>
        /// Action recebe um objPessoa para criar Pessoa do tipo Funcionario
        /// </summary>
        /// <param name="funcionario"> pessoa</param>
        /// <returns>Action p controle Usuario</returns>
        [Authorize(Roles = "Gerente, Administrador")]
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult CreateFuncionario(Pessoa funcionario)
        {
            try
            {
                funcionario.cpf = Ultis.Util.RemoverMascara(funcionario.cpf);
                funcionario.cpf = Ultis.Util.RemoverMascara(funcionario.cns);
                if (ModelState.IsValid)
                {
                    funcionario.TipoPessoa = TipoPessoa.Funcionario;
                    funcionario.dt_Cadastro = DateTime.Now;
                    pessoaBO.Inserir(funcionario);

SISPTD/SISPTD/Views/Pessoa/Details.cshtml
@model SISPTD.Models.Pessoa


<h3><i class="fa fa-info" aria-hidden="true"></i> Informações do Paciente</h3>
<div class="panel panel-default">
    <div class="panel-heading"><strong>@Html.DisplayFor(model => model.nome)</strong></div>
    <div class="panel-body">

    </div>
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.cpf)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.rg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.orgaoemissor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dt_Emissao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cns)
            </th>
        </tr>

        <tr>
            <td>
                @Html.DisplayFor(model => model.cpf)
            </td>
            <td>
                @Html.DisplayFor(model => model.rg)
            </td>
            <td>
                @Html.DisplayFor(model => model.orgaoemissor)
            </td>
            <td>
                @Html.DisplayFor(model => model.dt_Emissao)
            </td>
            <td>
                @Html.DisplayFor(model => model.cns)
            </td>
        </tr>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nome_Mae)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nome_Pai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.nome_Mae)
            </td>
            <td>
                @Html.DisplayFor(model => model.nome_Pai)
            </td>
            <td>
                @Html.DisplayFor(model => model.tel)
            </td>
            <td>
                @Html.DisplayFor(model => model.cel)
            </td>
            <td>
                @Html.DisplayFor(model => model.email)
            </td>
        </tr>
      
        <tr></tr>
    </table>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><strong>Acompanhantes</strong></h3>
    </div>
    <div class="panel-body">
      
    </div>
    <table class="table table-striped ">
        <tr>
            <th>
                @Html.LabelFor(model => model.cpf, new { @class = "control-label" })
            </th>
            <th>
                @Html.LabelFor(model => model.nome, new { @class = "control-label" })
            </th>
            <th>
                @Html.LabelFor(model => model.rg, new { @class = "control-label" })
            </th>
            <th>
                @Html.LabelFor(model => model.orgaoemissor, new { @class = "control-label" })
            </th>
            <th>
                @Html.LabelFor(model => model.dt_Emissao, new { @class = "control-label" })
            </th>
            <th>
                @Html.LabelFor(model => model.cns, new { @class = "control-label" })
            </th>
            <th>
                @Html.Label("Editar" )
            </th>
        </tr>
        @foreach (var item in @ViewBag.acompanhante)
        {
            <tr>
                <td>
                    @item.cpf
                </td>
                <td>
                    @if (User.IsInRole("Medico"))
                    {
                        @Html.Raw("<p>"+item.nome+"</p>");
                    }
                    else
                    {
                        @item.nome
                        
                    }
                </td>
                <td>
                    @item.rg
                </td>
                <td>
                    @item.orgaoemissor
                </td>
                <td>
                    @item.dt_Emissao
                </td>
                <td>
                    @item.cns
                </td>
                <td>
                    <a class="btn-group btn-sm btn-primary" title="Editar Acompanhante" href="@Url.Action("EditarAcompanhante", "Pessoa",new { id= item.pessoaId })" aria-label="Skip to main navigation">
                        <i class="fa fa-pencil fa-lg" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        }
    </table>
</div>
<div class="well well-sm" style="height:50px;">
    @if (!User.IsInRole("Medico"))
    {
        <a class="btn btn-primary" href="@Url.Action("Edit",  new { id = Model.pessoaId })">Editar</a>

    }

    @*@Html.ActionLink("Voltar para lista", "Index", null, new { @class = "btn btn-link pull-right" })*@
    <a class="btn btn-success pull-right" href="#" onclick="history.back()">Voltar</a>
</div>

SISPTD/SISPTD/Views/Pessoa/Edit.cshtml
@model SISPTD.Models.Pessoa
<span class="text-danger pull-right"><i class="glyphicon glyphicon-info-sign "></i> Os campos em vermelho são de preenchimento obrigatório.</span>
<br />
 <a title="Adicionar Acompanhante" class="btn btn-primary" href="@Url.Action("CreateAcompanhante","Pessoa", new {acompanhanteId= Model.pessoaId })"><i class="fa fa-user-plus fa-lg" aria-hidden="true"></i> Acompanhante <span class="badge"> @ViewBag.acompanhante</span> </a>

@using (Html.BeginForm())
{
    @Html.HiddenFor(p=> p.pessoaId)
    @Html.HiddenFor(p=> p.TipoPessoa)
    @Html.HiddenFor(p => p.Endereco.enderecoId)

  @Html.Partial("_Formulario", Model)

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SISPTD/SISPTD/Views/Pessoa/_FormAcompanhante.cshtml
@model SISPTD.Models.Pessoa


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel panel-default">
        <div class="panel-body ">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">

                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("CPF *", new { @class = "" })
                        @Html.EditorFor(model => model.cpf, new { htmlAttributes = new { @class = "form-control cpf " } })
                        @Html.ValidationMessageFor(model => model.cpf, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6 ">
                    <div class="form-group ">
                        @Html.Label("Nome *", new { @class = "" })
                        @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = " uperText form-control" } })
                        @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="input-group ">


                        @Html.Label("Data de Nascimento * ")
                        @Html.EditorFor(model => model.dt_Nascimento, new { htmlAttributes = new { @class = "form-control date " } })
                        @Html.ValidationMessageFor(model => model.dt_Nascimento, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.rg, new { @class = "" })
                        @Html.EditorFor(model => model.rg, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.rg, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.orgaoemissor, new { @class = " " })
                        @Html.EditorFor(model => model.orgaoemissor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.orgaoemissor, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.dt_Emissao, new { @class = "" })
                        @Html.EditorFor(model => model.dt_Emissao, new { htmlAttributes = new { @class = "form-control date" } })
                        @Html.ValidationMessageFor(model => model.dt_Emissao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Cartão SUS *", new { @class = " " })
                        @Html.EditorFor(model => model.cns, new { htmlAttributes = new { @class = "form-control cns" } })
                        @Html.ValidationMessageFor(model => model.cns, "", new { @class = "text-danger" })

                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Mãe *", new { @class = " " })
                        @Html.EditorFor(model => model.nome_Mae, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nome_Mae, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Pai *", new { @class = "" })
                        @Html.EditorFor(model => model.nome_Pai, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nome_Pai, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.Label("Telefone *", new { @class = "" })
                        @Html.EditorFor(model => model.tel, new { htmlAttributes = new { @class = "form-control telefone" } })
                        @Html.ValidationMessageFor(model => model.tel, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.cel)
                        @Html.EditorFor(model => model.cel, new { htmlAttributes = new { @class = "form-control telefone" } })
                        @Html.ValidationMessageFor(model => model.cel, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.email)
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Endereco.cep)
                        @Html.EditorFor(model => model.Endereco.cep, new { htmlAttributes = new { @class = "form-control cep" } })
                        @Html.ValidationMessageFor(model => model.Endereco.cep, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.Label("Rua *")
                        @Html.EditorFor(model => model.Endereco.rua, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Endereco.rua, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Numero *")
                        @Html.EditorFor(model => model.Endereco.numero, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Endereco.numero, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.Label("Bairro *")
                        @Html.EditorFor(model => model.Endereco.bairro, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Endereco.bairro, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

        </div>
    </div>


    <div class="well well-sm">
        <button type="submit" name="name" class="btn btn-primary "> <i class="fa fa-floppy-o fa-lg"></i>  Gravar</button>
        <a class="btn btn-danger pull-right" href="@Url.Action("Index","Pessoa")"> <i class="fa fa-backward fa-lg"></i>  Voltar para Lista </a>
    </div>

}

SISPTD/SISPTD/Views/Pessoa/_FormManutencao.cshtml
@model SISPTD.Models.Pessoa

@using (Html.BeginForm("ManutencaoDeCadastro", "Pessoa", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-default">
        <div class="panel-heading ">
            <h4 class="panel-title"><i class="fa fa-book fa-lg"> </i> <strong> Manutenção de Cadastro </strong></h4>

        </div>

        <div class="panel-body">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-3">
                    @Html.Label("CPF")
                    <div class="input-group">
                        @Html.TextBox("buscarPessoaManutencao", Request.QueryString["CPF"], new { autofocus = "", @class = "  cpf col-md-2 form-control", placeholder = "Procure por CPF" })
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-success buscarPessoaManutencao">
                                <i class="fa fa-search fa-lg"></i> 
                            </button>
                        </span>
                    </div>
                </div>
                <div class="col-md-6 ">
                    <div class="form-group ">
                        @Html.Label("Nome *", new { @class = "" })
                        @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = " uperText form-control", @readonly = " readonly" } })
                        @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
                        <input type="hidden" name="idPessoaManutencao" id="idPessoaManutencao" value="" />
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Data de Nascimento * ", new { @class = "" })
                        @Html.EditorFor(model => model.dt_Nascimento, new { htmlAttributes = new { @class = "form-control date" ,@readonly = " readonly" } })
                        @Html.ValidationMessageFor(model => model.dt_Nascimento, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
               
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Cartão SUS *", new { @class = " " })
                        @Html.EditorFor(model => model.cns, new { htmlAttributes = new { @class = "form-control cns", @readonly = " readonly" } })
                        @Html.ValidationMessageFor(model => model.cns, "", new { @class = "text-danger" })

                    </div>
                </div>


                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("CRM *", new { @class = " " })
                        @Html.EditorFor(model => model.crm, new { htmlAttributes = new { @class = "form-control ", @readonly=" readonly" } })
                        @Html.ValidationMessageFor(model => model.crm, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="col-md-4 col-sm-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.TipoPessoa, htmlAttributes: new { @class = "control-label" })
                        @Html.EnumDropDownListFor(model => model.TipoPessoa, "", htmlAttributes: new { @class = "form-control chosen-select" })
                        @Html.ValidationMessageFor(model => model.TipoPessoa, "", new { @class = "text-danger" })
                    </div>
                </div>


            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Mãe *", new { @class = " " })
                        @Html.EditorFor(model => model.nome_Mae, new { htmlAttributes = new { @class = "form-control" , @readonly = " readonly" } })
                        @Html.ValidationMessageFor(model => model.nome_Mae, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Pai *", new { @class = "" })
                        @Html.EditorFor(model => model.nome_Pai, new { htmlAttributes = new { @class = "form-control", @readonly = " readonly" } })
                        @Html.ValidationMessageFor(model => model.nome_Pai, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.Label("Telefone *", new { @class = "" })
                        @Html.EditorFor(model => model.tel, new { htmlAttributes = new { @class = "form-control telefone", @readonly = " readonly" } })
                        @Html.ValidationMessageFor(model => model.tel, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.cel)
                        @Html.EditorFor(model => model.cel, new { htmlAttributes = new { @class = "form-control telefone", @readonly = " readonly" } })
                        @Html.ValidationMessageFor(model => model.cel, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.email)
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @readonly = " readonly" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>

                </div>
                @*<div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Endereco.cep)
                        @Html.EditorFor(model => model.Endereco.cep, new { htmlAttributes = new { @class = "form-control cep" } })
                        @Html.ValidationMessageFor(model => model.Endereco.cep, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                @*<div class="col-md-4">
                    <div class="form-group">
                        @Html.Label("Rua *")
                        @Html.EditorFor(model => model.Endereco.rua, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Endereco.rua, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Numero *")
                        @Html.EditorFor(model => model.Endereco.numero, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Endereco.numero, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.Label("Bairro *")
                        @Html.EditorFor(model => model.Endereco.bairro, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Endereco.bairro, "", new { @class = "text-danger" })
                    </div>
                </div>*@
            </div>
        </div>
    </div>

    <div class="well well-sm">
        <button type="submit" name="name" class="btn btn-primary "> <i class="fa fa-floppy-o fa-lg"></i>  Gravar</button>
        <a class="btn btn-success pull-right" href="@Request.UrlReferrer"> <i class="fa fa-arrow-left fa-lg"></i>  Voltar para Lista </a>
    </div>

}
<script>
    var urlManutencao = '@Url.Action("ManutencaoDeCadastroBusca","Pessoa")';
</script>